travis, test: Add testssl tests

diff --git a/util/test b/util/test
--- a/util/test
+++ b/util/test
@@ -21,6 +21,76 @@ function ensure {
     || die "Failed to run '$*'. Aborting."
 }
 
+function test_lint {
+  shellcheck "${TWA}"
+
+  echo "${FUNCNAME[0]}: OK"
+}
+
+function test_twa_and_tscore {
+  twa_output=$("${TWA}" -v "${TEST_DOMAIN}")
+
+  [[ -n "${twa_output}" ]] || die "Empty twa output"
+
+  # TODO: Test to ensure twa_output doesn't contain color codes.
+
+  tscore_output=$("${TSCORE}" <<< "${twa_output}")
+
+  [[ -n "${tscore_output}" ]] || die "Empty tscore output"
+
+  read -r score \
+          npasses \
+          nmehs \
+          nfailures \
+          nunknowns \
+          nskips \
+          totally_screwed <<< "${tscore_output}"
+
+  [[ "${score}" -ge 0 && "${score}" -le 100 ]] || die "Bizarre total score: ${score}"
+  [[ "${npasses}" -ge 0 ]] || die "Negative passes? ${npasses}"
+  [[ "${nmehs}" -ge 0 ]] || die "Negative mehs? ${nmehs}"
+  [[ "${nfailures}" -ge 0 ]] || die "Negative failures? ${nfailures}"
+  [[ "${nunknowns}" -ge 0 ]] || die "Negative unknowns? ${nunknowns}"
+  [[ "${nskips}" -ge 0 ]] || die "Negative skips? ${nskips}"
+  [[ "${totally_screwed}" -eq 0 || "${totally_screwed}" -eq 1 ]] \
+      || die "totally_screwed not 0 or 1: ${totally_screwed}"
+
+  echo "${FUNCNAME[0]}: OK"
+}
+
+function test_twa_testssl {
+  installed testssl || { echo "${FUNCNAME[0]}: SKIP"; return; }
+
+  twa_output=$("${TWA}" -vs "${TEST_DOMAIN}")
+
+  [[ -n "${twa_output}" ]] || die "Empty twa output"
+
+  # TODO: Test to ensure twa_output doesn't contain color codes.
+
+  tscore_output=$("${TSCORE}" <<< "${twa_output}")
+
+  [[ -n "${tscore_output}" ]] || die "Empty tscore output"
+
+  read -r score \
+          npasses \
+          nmehs \
+          nfailures \
+          nunknowns \
+          nskips \
+          totally_screwed <<< "${tscore_output}"
+
+  [[ "${score}" -ge 0 && "${score}" -le 100 ]] || die "Bizarre total score: ${score}"
+  [[ "${npasses}" -ge 0 ]] || die "Negative passes? ${npasses}"
+  [[ "${nmehs}" -ge 0 ]] || die "Negative mehs? ${nmehs}"
+  [[ "${nfailures}" -ge 0 ]] || die "Negative failures? ${nfailures}"
+  [[ "${nunknowns}" -ge 0 ]] || die "Negative unknowns? ${nunknowns}"
+  [[ "${nskips}" -ge 0 ]] || die "Negative skips? ${nskips}"
+  [[ "${totally_screwed}" -eq 0 || "${totally_screwed}" -eq 1 ]] \
+      || die "totally_screwed not 0 or 1: ${totally_screwed}"
+
+  echo "${FUNCNAME[0]}: OK"
+}
+
 TWA="${TWA:-./twa}"
 TSCORE="${TSCORE:-./tscore}"
 TEST_DOMAIN="${TEST_DOMAIN:-example.com}"
@@ -31,34 +101,9 @@ TEST_DOMAIN="${TEST_DOMAIN:-example.com}"
 
 ensure installed shellcheck
 
-shellcheck "${TWA}"
+test_lint
+test_twa_and_tscore
+test_twa_testssl
+# TODO(ww): Add a test to ensure valid CSV output in CSV mode
 
-twa_output=$("${TWA}" "${TEST_DOMAIN}")
-
-[[ -n "${twa_output}" ]] || die "Empty twa output"
-
-# TODO: Test to ensure twa_output doesn't contain color codes.
-
-tscore_output=$("${TSCORE}" <<< "${twa_output}")
-
-[[ -n "${tscore_output}" ]] || die "Empty tscore output"
-
-read -r score \
-        npasses \
-        nmehs \
-        nfailures \
-        nunknowns \
-        nskips \
-        totally_screwed <<< "${tscore_output}"
-
-[[ "${score}" -ge 0 && "${score}" -le 100 ]] || die "Bizarre total score: ${score}"
-[[ "${npasses}" -ge 0 ]] || die "Negative passes? ${npasses}"
-[[ "${nmehs}" -ge 0 ]] || die "Negative mehs? ${nmehs}"
-[[ "${nfailures}" -ge 0 ]] || die "Negative failures? ${nfailures}"
-[[ "${nunknowns}" -ge 0 ]] || die "Negative unknowns? ${nunknowns}"
-[[ "${nskips}" -ge 0 ]] || die "Negative skips? ${nskips}"
-[[ "${totally_screwed}" -eq 0 || "${totally_screwed}" -eq 1 ]] \
-    || die "totally_screwed not 0 or 1: ${totally_screwed}"
-
-echo "OK"
 exit 0
